# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2gui.ui'
# Created by: PyQt5 UI code generator 5.15.2

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon('sampfresh.ico'))
        MainWindow.resize(1046, 526)
        MainWindow.setFixedSize(1046, 526)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(24, 24, 24);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 691, 471))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addressListLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.addressListLabel.setFont(font)
        self.addressListLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.addressListLabel.setObjectName("addressListLabel")
        self.gridLayout_4.addWidget(self.addressListLabel, 0, 2, 1, 1)
        self.hostnameListLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.hostnameListLabel.setFont(font)
        self.hostnameListLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.hostnameListLabel.setObjectName("hostnameListLabel")
        self.gridLayout_4.addWidget(self.hostnameListLabel, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sampTitleLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.sampTitleLabel.setFont(font)
        self.sampTitleLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.sampTitleLabel.setObjectName("sampTitleLabel")
        self.gridLayout.addWidget(self.sampTitleLabel, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.freshTitleLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.freshTitleLabel.setFont(font)
        self.freshTitleLabel.setStyleSheet("color: rgb(0, 112, 3);")
        self.freshTitleLabel.setObjectName("freshTitleLabel")
        self.gridLayout.addWidget(self.freshTitleLabel, 0, 1, 1, 1)
        self.subtitleLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.subtitleLabel.setFont(font)
        self.subtitleLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.gridLayout.addWidget(self.subtitleLabel, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget.setStyleSheet("border-color: rgb(255, 255, 127);\n"
"selection-background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(350)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 0, 4, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(710, 10, 321, 178))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.deleteBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.deleteBtn.setObjectName("deleteBtn")
        self.gridLayout_3.addWidget(self.deleteBtn, 4, 0, 1, 2)
        self.hostnameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.hostnameLabel.setFont(font)
        self.hostnameLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.hostnameLabel.setObjectName("hostnameLabel")
        self.gridLayout_3.addWidget(self.hostnameLabel, 0, 0, 1, 1)
        self.hostnameLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(16)
        self.hostnameLine.setFont(font)
        self.hostnameLine.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.hostnameLine.setObjectName("hostnameLine")
        self.gridLayout_3.addWidget(self.hostnameLine, 0, 1, 1, 1)
        self.addressLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.addressLabel.setFont(font)
        self.addressLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.addressLabel.setObjectName("addressLabel")
        self.gridLayout_3.addWidget(self.addressLabel, 1, 0, 1, 1)
        self.addressLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(16)
        self.addressLine.setFont(font)
        self.addressLine.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.addressLine.setObjectName("addressLine")
        self.gridLayout_3.addWidget(self.addressLine, 1, 1, 1, 1)
        self.addBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        self.addBtn.setFont(font)
        self.addBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.addBtn.setObjectName("addBtn")
        self.gridLayout_3.addWidget(self.addBtn, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 2)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(710, 180, 319, 300))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.connectBtn = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        self.connectBtn.setFont(font)
        self.connectBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 112, 3);")
        self.connectBtn.setObjectName("connectBtn")
        self.gridLayout_5.addWidget(self.connectBtn, 3, 0, 1, 2)
        self.discordCheckbox = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(14)
        self.discordCheckbox.setFont(font)
        self.discordCheckbox.setStyleSheet("color: rgb(255, 255, 255);")
        self.discordCheckbox.setObjectName("discordCheckbox")
        self.gridLayout_5.addWidget(self.discordCheckbox, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 4, 0, 1, 2)
        self.copyrightLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.copyrightLabel.setFont(font)
        self.copyrightLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.gridLayout_5.addWidget(self.copyrightLabel, 10, 1, 1, 1)
        self.versionLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.versionLabel.setFont(font)
        self.versionLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_5.addWidget(self.versionLabel, 9, 1, 1, 1, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 2)
        self.nicknameLine = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(16)
        self.nicknameLine.setFont(font)
        self.nicknameLine.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.nicknameLine.setObjectName("nicknameLine")
        self.gridLayout_5.addWidget(self.nicknameLine, 2, 0, 1, 2)
        self.discordLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.discordLabel.setFont(font)
        self.discordLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.discordLabel.setObjectName("discordLabel")
        self.gridLayout_5.addWidget(self.discordLabel, 6, 1, 1, 1)
        self.favServersCheckbox = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(14)
        self.favServersCheckbox.setFont(font)
        self.favServersCheckbox.setStyleSheet("color: rgb(255, 255, 255);")
        self.favServersCheckbox.setObjectName("favServersCheckbox")
        self.gridLayout_5.addWidget(self.favServersCheckbox, 7, 0, 1, 1)
        self.sampFavoritesLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.sampFavoritesLabel.setFont(font)
        self.sampFavoritesLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.sampFavoritesLabel.setObjectName("sampFavoritesLabel")
        self.gridLayout_5.addWidget(self.sampFavoritesLabel, 7, 1, 1, 1)
        self.nicknameLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.nicknameLabel.setFont(font)
        self.nicknameLabel.setStyleSheet("color: rgb(172, 172, 172);")
        self.nicknameLabel.setObjectName("nicknameLabel")
        self.gridLayout_5.addWidget(self.nicknameLabel, 1, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 8, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 0);")
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuGithub_repository = QtWidgets.QMenu(self.menubar)
        self.menuGithub_repository.setAutoFillBackground(False)
        self.menuGithub_repository.setStyleSheet("color: rgb(255, 255, 255);")
        self.menuGithub_repository.setObjectName("menuGithub_repository")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGithub_repositoryh = QtWidgets.QAction(MainWindow)
        self.actionGithub_repositoryh.setObjectName("actionGithub_repositoryh")
        self.menuGithub_repository.addAction(self.actionGithub_repositoryh)
        self.menubar.addAction(self.menuGithub_repository.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SA:MP Fresh"))
        self.addressListLabel.setText(_translate("MainWindow", "Ip Address"))
        self.hostnameListLabel.setText(_translate("MainWindow", "HostName"))
        self.sampTitleLabel.setText(_translate("MainWindow", "SA:MP"))
        self.freshTitleLabel.setText(_translate("MainWindow", "FRESH"))
        self.subtitleLabel.setText(_translate("MainWindow", "A custom Launcher for SA:MP"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hostname"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "asd"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "www.google.com"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.deleteBtn.setText(_translate("MainWindow", "Delete Server"))
        self.hostnameLabel.setText(_translate("MainWindow", "HostName"))
        self.addressLabel.setText(_translate("MainWindow", "IP Address"))
        self.addBtn.setText(_translate("MainWindow", "Add Server"))
        self.connectBtn.setText(_translate("MainWindow", "Connect"))
        self.discordCheckbox.setText(_translate("MainWindow", "Connect with Discord"))
        self.copyrightLabel.setText(_translate("MainWindow", "© 2021 - 2022 ne0de and le01q"))
        self.versionLabel.setText(_translate("MainWindow", "Version 0.0.2"))
        self.discordLabel.setText(_translate("MainWindow", "Enables a Discord Rich Presence"))
        self.favServersCheckbox.setText(_translate("MainWindow", "SA-MP Favorite servers"))
        self.sampFavoritesLabel.setText(_translate("MainWindow", "Uses sa-mp favorite servers"))
        self.nicknameLabel.setText(_translate("MainWindow", "Your Nickname"))
        self.menuGithub_repository.setTitle(_translate("MainWindow", "About"))
        self.actionGithub_repositoryh.setText(_translate("MainWindow", "Github Repository"))
